14_associations/starter_code/rewlsy/config/routes.rb
Rails.application.routes.draw do
  root 'stories#index'

  resources :stories do
      resources :comments, only: :create
  end
  
  resources :sessions, only: [:new, :create]
  get '/logout', to: "sessions#destroy", as: 'logout'
  

end

14_associations/starter_code/rewlsy/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :story
end

14_associations/starter_code/rewlsy/app/models/story.rb
class Story < ActiveRecord::Base
<<<<<<< HEAD
  belongs_to :user
  has_many :comments
  has_many :commenters, through: :comments, source: :user

=======
 belongs_to :user
 
>>>>>>> 7c2c1aa465733377ee3216fec5068355cdabc0e6
  validates :title, :category, :link, :upvotes, presence: true
  
  def self.search(query)
    where("title LIKE :query OR category LIKE :query", query: "%#{query}%")
  end
end

14_associations/starter_code/rewlsy/app/models/user.rb
class User < ActiveRecord::Base
  has_many :stories
<<<<<<< HEAD
  has_many :comments

=======
>>>>>>> 7c2c1aa465733377ee3216fec5068355cdabc0e6

  validates :username, :password, presence: true
  validates :username, uniqueness: true

  def self.create_with_password(username, password)
    hash = password_hash(password)
    User.create(username: username, password: hash)
  end

  def self.find_authenticated_user(username, password)
    User.where(username:username, password: password_hash(password)).first
  end

  private 
  def self.password_hash(password)
    return Digest::SHA2.hexdigest(password)
  end
end

user - user.first
user.username
user.stories this gives you an array
user.stories.count
my_story = Story.find(1)
my_story.user
story.user , this will return one user object
becuaes a user has many stories, we can ask user object to create a story for us and link it up already
stories.create(title: "crazy", link: "Google.com", upvotes: 1, category: 'news')
story_two = user.stories.last

need it in the schema
it added user:id, story:id


story has_many :commenters, through :comments, source :user

14_associations/starter_code/rewlsy/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    safe_comment = params.require(:comment).permit(:post)
    story_id = params[:story_id]
    story = Story.find(story_id)
    @comment = current_user.comments.build safe_comment
    @comment.story = story
    @comment.save
    redirect_to @comment.story
  end
end

14_associations/starter_code/rewlsy/app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]
  def index
    @stories = Story.search(params[:q])
  end

  def new
    @story = Story.new
  end

  def create
    safe_story_params = params.require(:story).permit(:title, :link, :category)
    @story = current_user.stories.build safe_story_params.merge(:upvotes => 1)

    if @story.save
      redirect_to @story
    else
      render :new
    end
  end

  def show
    @story = Story.find params[:id]
    @comment = Comment.new(:story => @story)
  end

end

14_associations/starter_code/rewlsy/app/helpers/comments_helper.rb
module CommentsHelper
end

14_associations/starter_code/rewlsy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rewlsy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'stories/search'%>
<% if logged_in? %>
Hi, <%= current_user.username%> - <%= link_to 'Add new story', new_story_path%> | <%= link_to "Logout", logout_path %>
<%else%>
<%= link_to "Login", new_session_path %>
<%end%>
<hr/>
<% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
  <%= yield %>


</body>
</html>

14_associations/starter_code/rewlsy/app/views/stories/show.html.erb
<<<<<<< HEAD
<h1><%= @story.title %> -  <%= "Posted by #{@story.user.username}" if @story.user.present?%></h1>
=======
<h1><%= @story.title %> -Posted by <%=@story.user.username if @story.user.present?%></h1>
>>>>>>> 7c2c1aa465733377ee3216fec5068355cdabc0e6
<p><%= link_to @story.link, @story.link %>
<p><%= link_to "Back to home page", root_path %></p>

<%= form_for [@story, @comment] do |f| %>
  <p>
    <%= f.text_area :post, placeholder: "Add a comment...", :rows => 8, :cols => 40 %>
  </p>
  <%= f.submit %>
<% end %>



<ul class="comments">
  <% @story.comments.each do |comment| %>
    <li><%= "#{comment.user.try(:username)} posted: #{comment.post}" %></li>
  <% end %>
</ul>